### ISSUE TITLE
Contributor

### ISSUE THREAD

**Issue by Schrank** [firegento/magento-performance-tweaks#18]
Can you please add at least two contributor/maintainer to the readme?

**Comment by kkrieger85** [comment]
@all-contributors add

**Comment by kkrieger85** [comment]
@all-contributors init

**Comment by kkrieger85** [comment]
@all-contributors please add @schrank for code, doc

**Comment by kkrieger85** [comment]
@all-contributors please add @sim for review, maintenance

**Comment by kkrieger85** [comment]
@all-contributors please add @sprankhub for review, maintenance

**Comment by kkrieger85** [comment]
@all-contributors please add @quafzi @kkrieger85 @LlZARD @toonvd @sylvainraye  @jeroenvermeulen @infabo @erfanimani @Flyingmana for code

**Comment by kkrieger85** [comment]
@all-contributors please add @kkrieger85 for code

**Comment by kkrieger85** [comment]
@all-contributors please add @LlZARD  for code

**Comment by kkrieger85** [comment]
@all-contributors please add @toonvd  for code

**Comment by kkrieger85** [comment]
@all-contributors please add @sylvainraye  for code

**Comment by kkrieger85** [comment]
@all-contributors please add @jeroenvermeulen  for code

**Comment by kkrieger85** [comment]
@all-contributors please add @infabo  for code

**Comment by kkrieger85** [comment]
@all-contributors please add @Flyingmana  for code

**Comment by kkrieger85** [comment]
@all-contributors please add @erfanimani  for code

**Comment by kkrieger85** [comment]
Close after PR #40, #39, #38, #37, #36, #35, #34, #33

**Comment by kkrieger85** [comment]
@all-contributors please add @sylvainraye for code

**Comment by kkrieger85** [comment]
@all-contributors please add @sylvainraye for code

**Comment by kkrieger85** [comment]
@all-contributors please add @erfanimani for code

**Comment by kkrieger85** [comment]
@all-contributors please add @Flyingmana for code

**Comment by kkrieger85** [comment]
@all-contributors please add @jeroenvermeulen for code

**Comment by kkrieger85** [comment]
@all-contributors please add @infabo for code

**Comment by kkrieger85** [comment]
Added all contributors: https://github.com/firegento/magento-performance-tweaks#contributors

if someone is missing, please create new issue
